---
  url: "http://hmg.nflix.com"
  database: 
    host: '10.20.10.5'
    dbname: "nflix"
    user: "postgres"
    password: "qaninja")
  users: 
    cat_manager: 
     email: "juca@stark.com"
     pass: "pwd123"